set shiftwidth=4
set softtabstop=4
set expandtab
set tabstop=4
set autoindent
set smartindent
set cindent
set mouse-=a
filetype plugin indent on
syntax on
set clipboard=unnamedplus

" copy/paste without auto-indent
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
    set pastetoggle=<Esc>[201~
    set paste
return ""
endfunction

