" editor setup
set shiftwidth=4
set softtabstop=4
set expandtab
set tabstop=4
set autoindent
set smartindent
set cindent
set mouse-=a
filetype plugin indent on
syntax on
set clipboard=unnamedplus

" automatically set paste mode when pasting in insert mode (no auto-indent)
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
function! XTermPasteBegin()
    set pastetoggle=<Esc>[201~
    set paste
    return ""
endfunction

" always start in top-left corner of a gitcommit
autocmd FileType gitcommit call setpos('.', [0, 1, 1, 0])

